
spring:
  datasource:
      name: dev
      url: jdbc:mysql://47.93.16.97:3306/wechat?&useSSL=false
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      logSlowSql: true
server:
  port: 8008
mybatis:
    basepackage: com.github.aidan.wechat.account.dao
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
adsl:
  host: 157.52.202.20
  port: 20398
  pwd: q123456
  user: root