eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    a-s-g-name: 123456789
  client:
      service-url:
        defaultZone: http://127.0.0.1:15002/eureka/

server:
  port: 9003
spring:
  application:
    name: spring-boot-1
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
